/**
 * Photography credits for the menu.
 *
 * Generated by `scripts/apply-menu-photos.ts` — do not edit by hand. Every
 * dish photo comes from an openly licensed image found through the Openverse
 * API and is cropped to 1200x900. Items without an entry here fall back to the
 * deterministic SVG artwork in `src/lib/menu-artwork.ts`.
 */

export type MenuPhoto = {
  /** Public path served from `public`. */
  file: string;
  /** Original title, used for alt text and attribution. */
  title: string;
  creator: string;
  /** SPDX-style licence label, e.g. "CC BY 2.0". */
  license: string;
  /** Page a reader can follow to verify the licence. */
  landing: string;
};

export const menuPhotos: Record<string, MenuPhoto> = {
  'truffle-parmesan-fries': {
    file: '/images/menu/truffle-parmesan-fries.jpg',
    title: 'Truffle Parmesan Fries',
    creator: 'mark6mauno',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/98147195@N00/51353374528',
  },
  'charred-corn-ribs': {
    file: '/images/menu/charred-corn-ribs.jpg',
    title: 'Corn \'ribs\' at Fallow',
    creator: 'Bex.Walton',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/7831824@N04/51350858723',
  },
  'crispy-chicken-wings': {
    file: '/images/menu/crispy-chicken-wings.jpg',
    title: 'Fried chicken wings',
    creator: 'rick',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/35034361412@N01/2441131691',
  },
  'burrata-heirloom-tomato': {
    file: '/images/menu/burrata-heirloom-tomato.jpg',
    title: 'Heirloom Tomatoes with Burrata Salad',
    creator: 'eekim',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/63669472@N00/5063360323',
  },
  'crispy-calamari': {
    file: '/images/menu/crispy-calamari.jpg',
    title: 'Fried Calamari Rings',
    creator: 'coolmikeol',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/44094498@N03/6632175159',
  },
  'feastcraft-smash-burger': {
    file: '/images/menu/feastcraft-smash-burger.jpg',
    title: 'Smash Burger',
    creator: 'Haydn Blackey',
    license: 'BY-SA 2.0',
    landing: 'https://www.flickr.com/photos/54549113@N00/20480125941',
  },
  'crispy-chicken-burger': {
    file: '/images/menu/crispy-chicken-burger.jpg',
    title: 'Crispy chicken burger at the Penny Farthing',
    creator: 'Ruth and Dave',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/95142644@N00/29059005563',
  },
  'mushroom-swiss-melt': {
    file: '/images/menu/mushroom-swiss-melt.jpg',
    title: 'Mmm... Mushroom Swiss burger with garlic ketchup',
    creator: 'jeffreyw',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/7927684@N03/18463383803',
  },
  'spicy-chicken-tacos': {
    file: '/images/menu/spicy-chicken-tacos.jpg',
    title: 'Mmm... grilled chicken tacos',
    creator: 'jeffreyw',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/7927684@N03/9416723321',
  },
  'miso-glazed-salmon': {
    file: '/images/menu/miso-glazed-salmon.jpg',
    title: 'Miso Glazed Salmon. #YUM #foodie #food #enjoying #foodporn #foodgasm #foodstagram #salmon #fish #seafood #dinner #dinnertime #photos #foodlover #foodpics #foodblogger #healthy #foodart #foodoftheday #monday #brunch #instafood #instagood',
    creator: 'organicboi',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/141471286@N06/27220625440',
  },
  'slow-braised-short-rib': {
    file: '/images/menu/slow-braised-short-rib.jpg',
    title: 'Braised Beef Short Rib w/ Unagi',
    creator: 'eekim',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/63669472@N00/3073044969',
  },
  'thai-green-curry': {
    file: '/images/menu/thai-green-curry.jpg',
    title: 'Thai green curry and rice',
    creator: 'pelican',
    license: 'BY-SA 2.0',
    landing: 'https://www.flickr.com/photos/85936780@N00/5584548469',
  },
  'wild-mushroom-risotto': {
    file: '/images/menu/wild-mushroom-risotto.jpg',
    title: 'Mushroom Risotto',
    creator: 'davegammon.media',
    license: 'BY-SA 2.0',
    landing: 'https://www.flickr.com/photos/35897104@N08/6386799545',
  },
  'chargrilled-chicken-steak': {
    file: '/images/menu/chargrilled-chicken-steak.jpg',
    title: 'Grilled Chicken Steak',
    creator: 'monirquazi',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/36206937@N02/3649822984',
  },
  'truffle-mushroom-pizza': {
    file: '/images/menu/truffle-mushroom-pizza.jpg',
    title: 'Mushroom pizza',
    creator: 'Ben Sutherland',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/60179301@N00/6996502661',
  },
  'spicy-pepperoni-pizza': {
    file: '/images/menu/spicy-pepperoni-pizza.jpg',
    title: 'Pepperoni Pizza',
    creator: 'bshamblen',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/23972840@N04/27566605040',
  },
  'spicy-vodka-rigatoni': {
    file: '/images/menu/spicy-vodka-rigatoni.jpg',
    title: 'Mmm... rigatoni with vodka sauce',
    creator: 'jeffreyw',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/7927684@N03/14991321641',
  },
  'carbonara': {
    file: '/images/menu/carbonara.jpg',
    title: 'Spaghetti carbonara',
    creator: 'stu_spivack',
    license: 'BY-SA 2.0',
    landing: 'https://www.flickr.com/photos/35034346243@N01/34677096',
  },
  'harvest-grain-bowl': {
    file: '/images/menu/harvest-grain-bowl.jpg',
    title: 'Buddha bowl',
    creator: 'AdrienChd',
    license: 'BY-SA 2.0',
    landing: 'https://www.flickr.com/photos/143027776@N06/42221121840',
  },
  'grilled-chicken-caesar': {
    file: '/images/menu/grilled-chicken-caesar.jpg',
    title: 'Grilled Chicken Caesar Salad - Automatic Cafe',
    creator: 'avlxyz',
    license: 'BY-SA 2.0',
    landing: 'https://www.flickr.com/photos/10559879@N00/2259686201',
  },
  'prawn-avocado-salad': {
    file: '/images/menu/prawn-avocado-salad.jpg',
    title: 'Prawn Salad',
    creator: 'fusionstream',
    license: 'BY-SA 2.0',
    landing: 'https://www.flickr.com/photos/44566449@N00/104183551',
  },
  'roast-cauliflower-bowl': {
    file: '/images/menu/roast-cauliflower-bowl.jpg',
    title: 'Roasted Cauliflower Lentils Tahini and Naan',
    creator: 'Vegan Feast Catering',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/25128194@N02/3609281431',
  },
  'shoestring-fries': {
    file: '/images/menu/shoestring-fries.jpg',
    title: 'French fries with some homemade ketchup',
    creator: 'jeffreyw',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/7927684@N03/4955438962',
  },
  'garlic-butter-greens': {
    file: '/images/menu/garlic-butter-greens.jpg',
    title: 'sauteed spinach',
    creator: 'stu_spivack',
    license: 'BY-SA 2.0',
    landing: 'https://www.flickr.com/photos/35034346243@N01/3115548252',
  },
  'loaded-cheese-fries': {
    file: '/images/menu/loaded-cheese-fries.jpg',
    title: 'shake shack cheese fries',
    creator: 'goodiesfirst',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/49215102@N00/3864013284',
  },
  'spicy-buffalo-wings': {
    file: '/images/menu/spicy-buffalo-wings.jpg',
    title: 'Buffalo Wing',
    creator: 'John Kratz',
    license: 'BY-SA 2.0',
    landing: 'https://www.flickr.com/photos/32214524@N00/413860433',
  },
  'molten-chocolate-torte': {
    file: '/images/menu/molten-chocolate-torte.jpg',
    title: 'Molten chocolate cake. fig ice cream',
    creator: 'stu_spivack',
    license: 'BY-SA 2.0',
    landing: 'https://www.flickr.com/photos/35034346243@N01/105033462',
  },
  'basque-cheesecake': {
    file: '/images/menu/basque-cheesecake.jpg',
    title: 'Basque Cheesecake - An amazing dinner from Dishpatch and Jose Pizarro',
    creator: 'Haydn Blackey',
    license: 'BY-SA 2.0',
    landing: 'https://www.flickr.com/photos/54549113@N00/51627503082',
  },
  'pistachio-tiramisu': {
    file: '/images/menu/pistachio-tiramisu.jpg',
    title: 'Tiramisu',
    creator: 'Le Ciel Azuré',
    license: 'BY-SA 2.0',
    landing: 'https://www.flickr.com/photos/12057629@N04/4094706451',
  },
  'salted-caramel-cheesecake-jar': {
    file: '/images/menu/salted-caramel-cheesecake-jar.jpg',
    title: 'Cheesecake in a Jar',
    creator: 'AngryJulieMonday',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/33731571@N07/5770509726',
  },
  'salted-caramel-cold-brew': {
    file: '/images/menu/salted-caramel-cold-brew.jpg',
    title: 'Cold brew coffee',
    creator: 'Vanilla and lace',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/51029399@N04/7571000902',
  },
  'blood-orange-soda': {
    file: '/images/menu/blood-orange-soda.jpg',
    title: 'Blood Orange Juice',
    creator: 'John Loo',
    license: 'BY 2.0',
    landing: 'https://www.flickr.com/photos/8510225@N07/9286421176',
  },
  'mango-lassi': {
    file: '/images/menu/mango-lassi.jpg',
    title: 'mango lassi',
    creator: 'stu_spivack',
    license: 'BY-SA 2.0',
    landing: 'https://www.flickr.com/photos/35034346243@N01/2303821722',
  },
  'fresh-lemonade': {
    file: '/images/menu/fresh-lemonade.jpg',
    title: 'Lemonade Glass',
    creator: 'themet',
    license: 'CC0 1.0',
    landing: 'https://www.rawpixel.com/image/7962548/lemonade-glass',
  },
};
