/**
 * Crops the winning candidate for each dish into `public/images/menu` and
 * records attribution in `src/lib/menu-photos.ts`.
 *
 * Consumes the output of `score-photo-candidates.ts`. Where the automatic
 * ranking picked the wrong subject, pass an explicit override:
 *
 *   npx tsx scripts/apply-menu-photos.ts [candidates-dir] [ranked-dir] \
 *     --overrides "carbonara=4,truffle-mushroom-pizza=1"
 *
 * Every photo is normalised to 1200x900 (4:3) because that is the aspect ratio
 * of every menu image slot in the app.
 */
import { readFile, writeFile, mkdir, readdir, unlink } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import { menu } from "../prisma/menu-data";

type Candidate = {
  index: number;
  slug: string;
  query: string;
  title: string;
  creator: string;
  license: string;
  foreignLandingUrl: string;
  sourceUrl: string;
  file: string;
};

type Pick = {
  index: number;
  file: string;
  score: number;
  title: string;
  creator: string;
  license: string;
  foreignLandingUrl: string;
  sourceUrl: string;
};

type Ranking = Record<string, { pick: Pick | null; confidence: number }>;

const OUTPUT_WIDTH = 1200;
const OUTPUT_HEIGHT = 900;

const escapeForSingleQuotes = (value: string) => value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");

function parseArgs() {
  const argv = process.argv.slice(2);
  const positional = argv.filter((value, i) => {
    if (value.startsWith("--")) return false;
    const previous = argv[i - 1];
    return !previous?.startsWith("--");
  });
  const read = (flag: string, fallback: string) => {
    const at = argv.indexOf(flag);
    return at === -1 ? fallback : argv[at + 1];
  };

  const overrides: Record<string, number> = {};
  for (const pair of read("--overrides", "").split(",")) {
    const [slug, index] = pair.split("=");
    if (slug?.trim() && index) overrides[slug.trim()] = Number(index);
  }

  return {
    candidatesDir:
      positional[0] ?? path.join(process.cwd(), ".photo-candidates"),
    rankedDir: positional[1] ?? path.join(process.cwd(), ".photo-ranked"),
    overrides,
    outDir: read("--out", path.join(process.cwd(), "public", "images", "menu")),
    manifest: read("--manifest", path.join(process.cwd(), "src", "lib", "menu-photos.ts")),
    keepFallbacks: argv.includes("--keep-fallbacks"),
  };
}

async function main() {
  const { candidatesDir, rankedDir, overrides, outDir, manifest, keepFallbacks } =
    parseArgs();

  const candidates = JSON.parse(
    await readFile(path.join(candidatesDir, "candidates.json"), "utf8"),
  ) as Candidate[];
  const ranking = JSON.parse(
    await readFile(path.join(rankedDir, "ranking.json"), "utf8"),
  ) as Ranking;

  const bySlugIndex = new Map<string, Candidate>();
  for (const candidate of candidates) {
    bySlugIndex.set(`${candidate.slug}#${candidate.index}`, candidate);
  }

  await mkdir(outDir, { recursive: true });

  const entries: Array<{
    slug: string;
    name: string;
    category: string;
    file: string;
    title: string;
    creator: string;
    license: string;
    landing: string;
  }> = [];

  const missing: string[] = [];

  for (const category of menu) {
    for (const item of category.items) {
      const override = overrides[item.slug];
      const chosenIndex = override ?? ranking[item.slug]?.pick?.index;
      const candidate = bySlugIndex.get(`${item.slug}#${chosenIndex}`);

      if (!candidate) {
        missing.push(item.slug);
        continue;
      }

      const source = path.join(candidatesDir, candidate.file);
      const destination = path.join(outDir, `${item.slug}.jpg`);

      await sharp(source, { failOn: "none" })
        .rotate()
        .resize(OUTPUT_WIDTH, OUTPUT_HEIGHT, {
          fit: "cover",
          position: sharp.strategy.attention,
        })
        .jpeg({ quality: 82, progressive: true, mozjpeg: true })
        .toFile(destination);

      entries.push({
        slug: item.slug,
        name: item.name,
        category: category.name,
        file: `/images/menu/${item.slug}.jpg`,
        title: candidate.title,
        creator: candidate.creator,
        license: candidate.license,
        landing: candidate.foreignLandingUrl || candidate.sourceUrl,
      });

      console.log(
        `  ${item.slug.padEnd(30)} -> ${path.basename(destination)}  (${candidate.license})`,
      );
    }
  }

  const body = `/**
 * Photography credits for the menu.
 *
 * Generated by \`scripts/apply-menu-photos.ts\` — do not edit by hand. Every
 * dish photo comes from an openly licensed image found through the Openverse
 * API and is cropped to 1200x900. Items without an entry here fall back to the
 * deterministic SVG artwork in \`src/lib/menu-artwork.ts\`.
 */

export type MenuPhoto = {
  /** Public path served from \`public\`. */
  file: string;
  /** Original title, used for alt text and attribution. */
  title: string;
  creator: string;
  /** SPDX-style licence label, e.g. "CC BY 2.0". */
  license: string;
  /** Page a reader can follow to verify the licence. */
  landing: string;
};

export const menuPhotos: Record<string, MenuPhoto> = {
${entries
  .map(
    (entry) => `  '${entry.slug}': {
    file: '${entry.file}',
    title: '${escapeForSingleQuotes(entry.title)}',
    creator: '${escapeForSingleQuotes(entry.creator)}',
    license: '${escapeForSingleQuotes(entry.license)}',
    landing: '${escapeForSingleQuotes(entry.landing)}',
  },`,
  )
  .join("\n")}
};
`;

  await writeFile(manifest, body, "utf8");

  const credits = `# Menu photography credits

All dish photos are openly licensed images sourced through the
[Openverse](https://openverse.org/) API. They are cropped to 1200x900 and served
from this directory. Regenerate with:

\`\`\`
npx tsx scripts/fetch-menu-photos.ts --out .photo-candidates
npx tsx scripts/score-photo-candidates.ts .photo-candidates .photo-ranked
npx tsx scripts/apply-menu-photos.ts .photo-candidates .photo-ranked
\`\`\`

| Dish | Photo | Credit |
| --- | --- | --- |
${entries
  .map(
    (entry) =>
      `| ${entry.name} | [${entry.title.replace(/\|/g, "\\|")}](${entry.landing}) | ${entry.creator} · ${entry.license} |`,
  )
  .join("\n")}
`;
  await writeFile(path.join(outDir, "CREDITS.md"), credits, "utf8");

  if (!keepFallbacks) {
    const existing = await readdir(outDir);
    await Promise.all(
      existing
        .filter((name) => name.endsWith(".svg"))
        .map((name) => unlink(path.join(outDir, name))),
    );
  }

  console.log(`\n${entries.length} photos -> ${outDir}`);
  console.log(`credits -> ${manifest}`);
  if (missing.length) console.log(`\nno photo for: ${missing.join(", ")}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
